nginx:
  build: nginx
  links:
    - flask
    - bbmaster
  volumes_from:
    - wwwdata
  ports:
    - "8020:80"
wwwdata:
  image: busybox
  volumes:
    - /data/www

flask:
  build: flask
  links:
    - postgres
  volumes_from:
    - wwwdata

postgres:
  build: postgres
  volumes_from:
    - dbdata
dbdata:
  image: busybox
  volumes:
    - /var/lib/postgresql/data

bbdata:
  image: busybox
  volumes:
    - /data/buildbot
bbmaster:
  build: buildbot
  env_file: confidential.env
  links:
    - postgres
  volumes_from:
    - bbdata

bbwheezy64:
  build: buildbot/wheezy64
  env_file: confidential.env
  links:
    - bbmaster